const CONFIG = {
  introTitle: "Bé yêu à!",
  introDesc: `Trong một thế giới đầy rẫy những sự mơ hồ và không chắc chắn, có một điều duy nhất mà anh biết chắc chắn là tình cảm của anh dành cho em. Nó không phải là một cảm giác thoáng qua, mà là một ngọn lửa luôn rực cháy trong lòng anh. anh muốn chia sẻ mọi khoảnh khắc, mọi niềm vui và nỗi buồn trong cuộc đời này cùng với em.`,
  btnIntro: "hehe",
  title: "Phải chăng bé yêu đã yêu anh ngay từ cái nhìn đầu tiên 😙",
  desc: "Phải chăng bé yêu đã say ngay từ lúc thấy nụ cười ấy ",
  btnYes: "Vẫn cứ là thích dew <3",
  btnNo: "Không, Dew à :3",
  question: "Trên thế giới hơn 7 tỉ người mà sao bé yêu lại yêu anh <3",
  btnReply: "Gửi cho anh <3",
  reply: "Yêu thì yêu mà không yêu thì yêu <33333333",
  mess: "Anh biết mà 🥰. Yêu em nhiều nhiều 😘😘",
  messDesc: "Tối nay 00h anh qua đón bé yêu nha hehe.",
  btnAccept: "Okiiiii lun <3",
  messLink: "https://www.facebook.com/CoderThanhSon", 
};
